// Generated by gencpp from file commande/commandType.msg
// DO NOT EDIT!


#ifndef COMMANDE_MESSAGE_COMMANDTYPE_H
#define COMMANDE_MESSAGE_COMMANDTYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace commande
{
template <class ContainerAllocator>
struct commandType_
{
  typedef commandType_<ContainerAllocator> Type;

  commandType_()
    : rayon(0.0)
    , demi_ecart(0.0)
    , u(0.0)
    , w(0.0)  {
    }
  commandType_(const ContainerAllocator& _alloc)
    : rayon(0.0)
    , demi_ecart(0.0)
    , u(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef double _rayon_type;
  _rayon_type rayon;

   typedef double _demi_ecart_type;
  _demi_ecart_type demi_ecart;

   typedef double _u_type;
  _u_type u;

   typedef double _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::commande::commandType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::commande::commandType_<ContainerAllocator> const> ConstPtr;

}; // struct commandType_

typedef ::commande::commandType_<std::allocator<void> > commandType;

typedef boost::shared_ptr< ::commande::commandType > commandTypePtr;
typedef boost::shared_ptr< ::commande::commandType const> commandTypeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::commande::commandType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::commande::commandType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::commande::commandType_<ContainerAllocator1> & lhs, const ::commande::commandType_<ContainerAllocator2> & rhs)
{
  return lhs.rayon == rhs.rayon &&
    lhs.demi_ecart == rhs.demi_ecart &&
    lhs.u == rhs.u &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::commande::commandType_<ContainerAllocator1> & lhs, const ::commande::commandType_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace commande

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::commande::commandType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commande::commandType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande::commandType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande::commandType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande::commandType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande::commandType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::commande::commandType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4074ebba24351b6cc4dea7efb1a4d48f";
  }

  static const char* value(const ::commande::commandType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4074ebba24351b6cULL;
  static const uint64_t static_value2 = 0xc4dea7efb1a4d48fULL;
};

template<class ContainerAllocator>
struct DataType< ::commande::commandType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "commande/commandType";
  }

  static const char* value(const ::commande::commandType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::commande::commandType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 rayon\n"
"float64 demi_ecart\n"
"float64 u\n"
"float64 w\n"
"\n"
;
  }

  static const char* value(const ::commande::commandType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::commande::commandType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rayon);
      stream.next(m.demi_ecart);
      stream.next(m.u);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct commandType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::commande::commandType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::commande::commandType_<ContainerAllocator>& v)
  {
    s << indent << "rayon: ";
    Printer<double>::stream(s, indent + "  ", v.rayon);
    s << indent << "demi_ecart: ";
    Printer<double>::stream(s, indent + "  ", v.demi_ecart);
    s << indent << "u: ";
    Printer<double>::stream(s, indent + "  ", v.u);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMANDE_MESSAGE_COMMANDTYPE_H
