// Generated by gencpp from file commande/wheelType.msg
// DO NOT EDIT!


#ifndef COMMANDE_MESSAGE_WHEELTYPE_H
#define COMMANDE_MESSAGE_WHEELTYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace commande
{
template <class ContainerAllocator>
struct wheelType_
{
  typedef wheelType_<ContainerAllocator> Type;

  wheelType_()
    : w1(0.0)
    , w2(0.0)  {
    }
  wheelType_(const ContainerAllocator& _alloc)
    : w1(0.0)
    , w2(0.0)  {
  (void)_alloc;
    }



   typedef double _w1_type;
  _w1_type w1;

   typedef double _w2_type;
  _w2_type w2;





  typedef boost::shared_ptr< ::commande::wheelType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::commande::wheelType_<ContainerAllocator> const> ConstPtr;

}; // struct wheelType_

typedef ::commande::wheelType_<std::allocator<void> > wheelType;

typedef boost::shared_ptr< ::commande::wheelType > wheelTypePtr;
typedef boost::shared_ptr< ::commande::wheelType const> wheelTypeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::commande::wheelType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::commande::wheelType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::commande::wheelType_<ContainerAllocator1> & lhs, const ::commande::wheelType_<ContainerAllocator2> & rhs)
{
  return lhs.w1 == rhs.w1 &&
    lhs.w2 == rhs.w2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::commande::wheelType_<ContainerAllocator1> & lhs, const ::commande::wheelType_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace commande

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::commande::wheelType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commande::wheelType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande::wheelType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande::wheelType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande::wheelType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande::wheelType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::commande::wheelType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3c01d41a05dfc64b137725d37d1de39";
  }

  static const char* value(const ::commande::wheelType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3c01d41a05dfc64ULL;
  static const uint64_t static_value2 = 0xb137725d37d1de39ULL;
};

template<class ContainerAllocator>
struct DataType< ::commande::wheelType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "commande/wheelType";
  }

  static const char* value(const ::commande::wheelType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::commande::wheelType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 w1\n"
"float64 w2\n"
;
  }

  static const char* value(const ::commande::wheelType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::commande::wheelType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.w1);
      stream.next(m.w2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wheelType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::commande::wheelType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::commande::wheelType_<ContainerAllocator>& v)
  {
    s << indent << "w1: ";
    Printer<double>::stream(s, indent + "  ", v.w1);
    s << indent << "w2: ";
    Printer<double>::stream(s, indent + "  ", v.w2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMANDE_MESSAGE_WHEELTYPE_H
